project_id = "vprxcirjtzsxyllqjjyr"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-consistency]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.translate-report]
    verify_jwt = false
