
-- Auto-create valuation_assignment when valuation_request is submitted
CREATE OR REPLACE FUNCTION public.auto_create_assignment_on_request()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  _client_id uuid;
  _org_id uuid;
  _assignment_id uuid;
  _purpose valuation_purpose;
  _basis basis_of_value;
  _property_type property_type;
  _valuation_type valuation_type;
BEGIN
  -- Only act on new submitted requests without an assignment
  IF NEW.status != 'submitted' OR NEW.assignment_id IS NOT NULL THEN
    RETURN NEW;
  END IF;

  -- Find client_id from portal user
  SELECT id INTO _client_id FROM public.clients
  WHERE portal_user_id = NEW.client_user_id
  LIMIT 1;

  -- If no client found, try to create one from profile
  IF _client_id IS NULL THEN
    -- Get profile info
    DECLARE
      _profile record;
    BEGIN
      SELECT full_name_ar, phone INTO _profile FROM public.profiles
      WHERE user_id = NEW.client_user_id LIMIT 1;

      -- Get default org
      SELECT id INTO _org_id FROM public.organizations LIMIT 1;
      IF _org_id IS NULL THEN
        RAISE WARNING 'No organization found — cannot create assignment';
        RETURN NEW;
      END IF;

      -- Create client record
      INSERT INTO public.clients (
        name_ar, phone, email, organization_id, portal_user_id, client_status, client_type
      ) VALUES (
        COALESCE(NEW.client_name_ar, _profile.full_name_ar, 'عميل جديد'),
        COALESCE(NEW.client_phone, _profile.phone),
        NEW.client_email,
        _org_id,
        NEW.client_user_id,
        'portal',
        'individual'
      )
      RETURNING id INTO _client_id;
    END;
  ELSE
    -- Get org from existing client
    SELECT organization_id INTO _org_id FROM public.clients WHERE id = _client_id;
  END IF;

  IF _org_id IS NULL THEN
    SELECT id INTO _org_id FROM public.organizations LIMIT 1;
  END IF;

  IF _org_id IS NULL THEN
    RAISE WARNING 'No organization found — cannot create assignment';
    RETURN NEW;
  END IF;

  -- Map purpose (default to sale_purchase)
  _purpose := COALESCE(NEW.purpose, 'sale_purchase');

  -- Map basis_of_value
  _basis := COALESCE(NEW.basis_of_value, 'market_value');

  -- Map property_type (default to residential)
  _property_type := COALESCE(NEW.property_type, 'residential');

  -- Map valuation_type
  _valuation_type := COALESCE(NEW.valuation_type, 'real_estate');

  -- Create the assignment (reference_number auto-generated by existing trigger)
  INSERT INTO public.valuation_assignments (
    organization_id,
    client_id,
    created_by,
    property_type,
    purpose,
    basis_of_value,
    valuation_type,
    valuation_mode,
    status,
    reference_number,
    sequential_number,
    report_language,
    intended_users_ar,
    notes
  ) VALUES (
    _org_id,
    _client_id,
    NEW.client_user_id,
    _property_type,
    _purpose,
    _basis,
    _valuation_type,
    COALESCE(NEW.valuation_mode, 'field'),
    'submitted',
    '', -- will be overwritten by generate_reference_number trigger
    0,  -- will be overwritten by generate_reference_number trigger
    'ar',
    NEW.intended_users_ar,
    'طلب من بوابة العملاء'
  )
  RETURNING id INTO _assignment_id;

  -- Link request to assignment
  NEW.assignment_id := _assignment_id;
  NEW.client_id := _client_id;
  NEW.organization_id := _org_id;

  RETURN NEW;
END;
$$;

-- Drop if exists and recreate
DROP TRIGGER IF EXISTS trg_auto_create_assignment ON public.valuation_requests;
CREATE TRIGGER trg_auto_create_assignment
  BEFORE INSERT ON public.valuation_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_create_assignment_on_request();
